### ISSUE TITLE
【Bug 反馈】 Bilibili 顶栏收藏夹字体与背景重合

### ISSUE THREAD

**Issue by ExplodingDragon** [QIUZAIYOU/Stylish#1]
Bilibili 顶栏收藏夹字体与背景重合

如图所示：

![image](https://user-images.githubusercontent.com/33776693/111764018-b9208c00-88dd-11eb-86ea-70d7d7346f80.png)

版本：
- 浏览器 ：Microsoft Edge 89.0.774.54 
- 插件：[openstyles/stylus](https://github.com/openstyles/stylus)
- 主题版本：March 16, 2021 (commit: 0cb182e8445eaa31dc7311ab3f9acb11f3cfbf68)

**Comment by QIUZAIYOU** [comment]
已修复。没收到提示，不好意思这么久才看到。

**Comment by ExplodingDragon** [comment]
问题已解决 (～￣▽￣)～
