### ISSUE TITLE
b站视频页的字体颜色又变成黑的了

### ISSUE THREAD

**Issue by AKIs-z01** [QIUZAIYOU/Stylish#11]
b站视频页的字体颜色又变成黑的了，麻烦作者大大更新下
![Clip_20220313_220058](https://user-images.githubusercontent.com/51504776/158063121-46edd315-e402-4a5a-90ac-a824f92ab9df.jpg)

**Comment by QIUZAIYOU** [comment]
你的播放页更新了，我两个号到现在都还没给我推送更新，早就想适配了，B站不给我机会，愁死我了...

**Comment by AKIs-z01** [comment]
[www.bilibili.com.zip](https://github.com/QIUZAIYOU/Stylish/files/8359400/www.bilibili.com.zip)
![image](https://user-images.githubusercontent.com/51504776/160320942-e2c5ff7b-d1c5-4d94-aaa2-02642aa5df5c.png)
我扒了下页面不知道有没有用

**Comment by QIUZAIYOU** [comment]
> [www.bilibili.com.zip](https://github.com/QIUZAIYOU/Stylish/files/8359400/www.bilibili.com.zip) ![image](https://user-images.githubusercontent.com/51504776/160320942-e2c5ff7b-d1c5-4d94-aaa2-02642aa5df5c.png) 我扒了下页面不知道有没有用

收到，我来试试。

**Comment by QIUZAIYOU** [comment]
我这显示你文件里的页面结构还是旧版的，和你上面的截图还是不一样。
![微信截图_20220328113442](https://user-images.githubusercontent.com/26304262/160322179-4043f42c-1689-4a79-aa3c-c510d0b5f656.png)

**Comment by AKIs-z01** [comment]
噢对哦，这玩意外部扒的没登账号

**Comment by AKIs-z01** [comment]
我想想还有什么办法

**Comment by QIUZAIYOU** [comment]
搞不懂B站的测试推送机制怎么玩的，前两天连我几乎没用过的搜索页面都给我推新版测试了，播放页到现在这么久了就是不给推。- -

**Comment by AKIs-z01** [comment]
可能要经常看网页版吧

**Comment by AKIs-z01** [comment]
或者说是大会员还是账户等级

**Comment by AKIs-z01** [comment]
[bilibili.zip](https://github.com/QIUZAIYOU/Stylish/files/8359492/bilibili.zip)
这次大概可以

**Comment by QIUZAIYOU** [comment]
还是不行，打开后会显示一瞬间的旧版页面，之后就会变成视频丢失的空白页，能用调试模式截停到旧版页，但是没什么用。估计新版页需要发送请求并验证uid，本地文件没有。
![微信截图_20220328153110](https://user-images.githubusercontent.com/26304262/160348333-71ecdb72-784e-45d4-b4cd-eb594ae41347.png)
![微信截图_20220328154012](https://user-images.githubusercontent.com/26304262/160349890-0cf5bbd4-9900-417d-a420-2d664c78c7c6.png)
我每天都用B站，纯靠签到和看视频到5级，年度大会员，这都不给我推，而且我问客服了，就说会逐步夸大范围，但是没说时间，我是没辙了。

**Comment by AKIs-z01** [comment]
我上课无聊注册了新号，发现直接有新版体验![Screenshot_2022-03-29-10-24-13-455_com.mmbox.xbrowser.pro.jpg](https://user-images.githubusercontent.com/51504776/160520193-b73cdff2-5b22-42a2-957a-5f9137a74455.jpg)

**Comment by QIUZAIYOU** [comment]
牛逼，借同事手机号注册了一下果然是的。

**Comment by AKIs-z01** [comment]
好诶，那就拜托大佬了

**Comment by QIUZAIYOU** [comment]
已适配，若发现有未覆盖的地方请及时告诉我。
