### ISSUE TITLE
还有部分未适配

### ISSUE THREAD

**Issue by AKIs-z01** [QIUZAIYOU/Stylish#12]
视频选集
![image](https://user-images.githubusercontent.com/51504776/160664023-2db25813-d61f-408c-b3eb-41e4d98ba2da.png)
订阅页底部页码
![image](https://user-images.githubusercontent.com/51504776/160664112-fdf07c31-846f-40ac-a41e-25010bcb9f17.png)
最后一个不知道能不能做下，点赞投币收藏没颜色
![image](https://user-images.githubusercontent.com/51504776/160664271-0dbef7fc-a324-482a-a05e-516eaeafc3e6.png)

**Comment by QIUZAIYOU** [comment]
搞定，不过应该还有我没发现的，慢慢来。
