### ISSUE TITLE
播放页

### ISSUE THREAD

**Issue by AKIs-z01** [QIUZAIYOU/Stylish#14]
创作团队的字和背景
![image](https://user-images.githubusercontent.com/51504776/161676305-81b4f4c7-a073-4e5c-92a9-599994583bde.png)
往下拉后评论区背景
![image](https://user-images.githubusercontent.com/51504776/161676395-af7687ea-641e-472f-bfd5-de9a0fdc2cbd.png)

**Comment by AKIs-z01** [comment]
上面第一个是宽屏模式下的

**Comment by AKIs-z01** [comment]
追加一个
视频推荐首个视频
![image](https://user-images.githubusercontent.com/51504776/161678861-a4f2422a-79d0-4444-b2cc-5bd6d7ddc4a1.png)

**Comment by QIUZAIYOU** [comment]
其他修复了，但是评论区背景我这边显示是正常的，你再看看。

**Comment by AKIs-z01** [comment]
可能是某个插件影响的，纯净就没事了，谢谢大佬
