### ISSUE TITLE
[夜间哔哩] 动态里字体颜色匹配失效

### ISSUE THREAD

**Issue by letterk** [QIUZAIYOU/Stylish#16]
![图片](https://user-images.githubusercontent.com/9822709/171278205-c8d9bac2-f9d2-4e39-bf32-446d8e1cb724.png)

试了几个子域名, 只有`www`子域名匹配失效
应该又是新版的关系

**Comment by QIUZAIYOU** [comment]
已修复。估计是今天才刚换的新版，昨天还正常，这几天B站更新频繁，我一直在适配。🙃
