### ISSUE TITLE
视频播放页和创作中心

### ISSUE THREAD

**Issue by AKIs-z01** [QIUZAIYOU/Stylish#18]
![image](https://user-images.githubusercontent.com/51504776/188276138-65307fb5-5145-4498-a250-d0c51a35395b.png)
![image](https://user-images.githubusercontent.com/51504776/188276174-5208f8e5-a8bc-4277-9c00-897d1ebad25e.png)
两个页面有白色的没覆盖，希望作者大大更新一下

**Comment by AKIs-z01** [comment]
![image](https://user-images.githubusercontent.com/51504776/188276253-99133135-3ecb-476c-8775-598c9fa5cc6e.png)
创作中心还有部分字体是黑的

**Comment by QIUZAIYOU** [comment]
ok，我没发过视频所以创作中心好多页面没见过，现在借了我弟的号，可以适配了。

**Comment by QIUZAIYOU** [comment]
你图里的观看排行我这边没显示，这部分元素排列和你图里不一样，后续我再看看。
