### ISSUE TITLE
可以继续维护b站旧版播放页吗

### ISSUE THREAD

**Issue by letterk** [QIUZAIYOU/Stylish#20]
新版播放页, 非常的卡顿, 我尝试过几次, 最后都退回旧版了
![图片](https://github.com/QIUZAIYOU/Stylish/assets/9822709/0c3a3d18-d60a-462e-8857-d7b46acf9f8a)

**Comment by QIUZAIYOU** [comment]
好的，有时间我恢复下。

**Comment by QIUZAIYOU** [comment]
你是怎么退出新版的？我两个号都已经回不去旧版了。

**Comment by letterk** [comment]
> 



> 你是怎么退出新版的？我两个号都已经回不去旧版了。

https://greasyfork.org/zh-CN/scripts/455571-%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9-b%E7%AB%99-%E8%87%AA%E5%8A%A8%E5%9B%9E%E5%88%B0%E6%97%A7%E7%89%88%E9%A1%B5%E9%9D%A2

现在b站不给退回按钮了, 用这个脚本
