### ISSUE TITLE
哔哩哔哩的评论文字黑色

### ISSUE THREAD

**Issue by Teraflopst** [QIUZAIYOU/Stylish#24]
Stylus (版本 1.5.47) 安装哔哩哔哩样式，评论文字呈黑色，而 Stylus (beta) 则正常
测试：Microsoft Edge，Google Chrome

**Comment by QIUZAIYOU** [comment]
看了下，B站更新把页面部分元素放入 shadow-root 里面了，目前 Stylus 这种通过样式表修改页面样式的方法对 shadow-root 里面的元素不生效，如果B站全面推进这种形式，我这个样式可能就废了。

Stylus 仓库 21 年就有人提过这方面的 issue，但是并没有办法解决。[Support for ShadowRoot DOM #1212](https://github.com/openstyles/stylus/issues/1212)

先将评论区恢复为白底了，不然现在这样看着确实挺乱的。

**Comment by Teraflopst** [comment]
@QIUZAIYOU 那这个样式效果还可以，参考下是怎么实现的 https://userstyles.world/style/10951/bilibili-dark-night

**Comment by QIUZAIYOU** [comment]
我也反应过来了，CSS 变量能穿透 shadowRoot，变量名取的和官方的一样就能覆盖了。
有点儿意思，但是官方颜色分的太细，有可能会误伤，而且官方如果没用变量的话也还是改不了，不过应该没啥大问题，官方没用变量的情况也不算多，先这么用着。
