### ISSUE TITLE
哔哩哔哩历史记录页面疑似更新，样式会让封面显示不出来

### ISSUE THREAD

**Issue by noncharacter** [QIUZAIYOU/Stylish#25]
![QQ截图20241127165602](https://github.com/user-attachments/assets/b3fae1f2-1964-42bb-866a-fe51a23576e2)
![QQ截图20241127165431](https://github.com/user-attachments/assets/292dd11b-ccd6-4db8-89e1-876ed5514cdc)
![QQ截图20241127165800](https://github.com/user-attachments/assets/526424b5-9dff-4428-9c8b-7a46269c5c82)
如题。列表模式能显示信息但不显示封面；网格模式就什么都不显示了

**Comment by QIUZAIYOU** [comment]
已修复。
