### ISSUE TITLE
夜间斗鱼在一些直播间无法使用

### ISSUE THREAD

**Issue by SNANA51832** [QIUZAIYOU/Stylish#3]
比如那种赛事的直播间，我看XDD的就不行

![屏幕截图(34)](https://user-images.githubusercontent.com/77220918/133073296-53ed93aa-b115-4c8e-a7a8-9ff490859b6c.png)

**Comment by QIUZAIYOU** [comment]
斗鱼给部分直播间的装修毫无规律可言，修复一个直播间另一个可能就会出问题，非常恶心人，所以只靠样式来处理是不行的，如果想达到直播间页面只保留播放器的最佳效果的话，请在Tampermonkey上安装本人的这个非常简单的小脚本[斗鱼直播间播放器置顶](https://greasyfork.org/zh-CN/scripts/399600-%E6%96%97%E9%B1%BC%E7%9B%B4%E6%92%AD%E9%97%B4%E6%92%AD%E6%94%BE%E5%99%A8%E7%BD%AE%E9%A1%B6)，配合本样式使用即可。此脚本为半公开，只能通过链接访问。
PS：如果不想只保留播放器，而是对下方鱼吧等元素也有使用需求的话那只能暂时在此直播间停止使用本样式了。

**Comment by mingye33** [comment]
这个问题出现在www.douyu.com/topic/XXXXXXXXX   这种活动页面上，斗鱼和虎牙这类网站简直了，用了大佬的播放器置顶确实干净完美
