### ISSUE TITLE
斗鱼关注页，直播间封面显示不正常

### ISSUE THREAD

**Issue by dammu** [QIUZAIYOU/Stylish#5]
![image](https://user-images.githubusercontent.com/26609762/137721314-b2e90d8e-d4cc-4847-8384-f3473f3d09b8.png)
如图所示，右是鼠标放上去的时候，这时候会加载一个动态封面，这个正常。左是打开的正常状态，静态封面不显示。关掉样式就显示，自己看了看但没有解决。

**Comment by QIUZAIYOU** [comment]
不好意思刚看到，问题已修复。
