### ISSUE TITLE
Bilibili 的样式还有瑕疵

### ISSUE THREAD

**Issue by phoenix1917** [QIUZAIYOU/Stylish#7]
昨天b站更新了页面，一些按钮的位置调整了，视频和评论区的很多span样式调整了。现在脚本还没适配文字的颜色，用起来比较难受，麻烦更新一下，谢谢~
现在b站的字整体被改大了，总觉得很别扭，建议脚本里把字号改回原来的小字。

**Comment by QIUZAIYOU** [comment]
有问题的地方有截图吗？我刚看了视频和评论区暂时没发现有什么问题。

**Comment by phoenix1917** [comment]
![image](https://user-images.githubusercontent.com/7992404/148901037-f21d66c3-d78c-4b0b-9110-e3ae36f86c03.png)
我的播放页标题字的颜色始终没改过来。这个页上我也没有挂其他脚本，没有dark reader。

**Comment by phoenix1917** [comment]
![image](https://user-images.githubusercontent.com/7992404/148901656-e5828350-8e19-4dce-a289-89e6c0494798.png)

**Comment by phoenix1917** [comment]
bilibili助手没有开黑夜模式，应该不是其他脚本造成的冲突。我是用Stylus插件更新的，是不是代码更新的问题？

**Comment by QIUZAIYOU** [comment]
知道了，应该是你的号收到了新版播放页的灰度测试，我这边只收到了首页的新版测试，播放页还是旧的，所以我暂时还没办法适配，等我播放页也是新版之后会立即适配。你先切换到旧版试试看？

**Comment by phoenix1917** [comment]
哦，有这个可能，但是回到旧版只有首页能回去，播放页还是这样的。我等等吧。
需要我把新播放页的DOM tree发给你看看吗？

**Comment by QIUZAIYOU** [comment]
可以，感谢，你也可以先把没正确显示的地方的class值给我，我写进去试试。

**Comment by QIUZAIYOU** [comment]
已适配，若发现有未覆盖的地方请及时告诉我。
