### ISSUE TITLE
托管网站的夜间斗鱼版本错误？

### ISSUE THREAD

**Issue by noncharacter** [QIUZAIYOU/Stylish#9]
UserStyles.world上的是 Imported from https://cdn.jsdelivr.net/gh/33kk/uso-archive@flomaster/data/usercss/158117.user.css
版本为20210510.10.30
![QQ截图20220208002351](https://user-images.githubusercontent.com/19724779/152828910-b09d204c-c7c5-486d-b14b-f90412a454ea.png)
如图 点击安装后是此版本

**Comment by noncharacter** [comment]
显示的是7号更新的，但是点击install却是安装那个archive版本的
![QQ截图20220208003328](https://user-images.githubusercontent.com/19724779/152830885-40c0eba7-d5ed-4adb-b9c9-207cdcc3d9d8.png)

**Comment by QIUZAIYOU** [comment]
最近这几天 userstyles.world 这个托管平台确实有这个问题，已经更新了，但是安装界面却是旧版。
不过我刚才看好像他们已经修复了。

**Comment by noncharacter** [comment]
> 最近这几天 userstyles.world 这个托管平台确实有这个问题，已经更新了，但是安装界面却是旧版。 不过我刚才看好像他们已经修复了。

刚才去看了下 还是那个版本 用不同网络设备都是那个..但是在这网站上你其它的样式是最新的，不明白为啥唯独斗鱼这个会出毛病

**Comment by noncharacter** [comment]
> 最近这几天 userstyles.world 这个托管平台确实有这个问题，已经更新了，但是安装界面却是旧版。 不过我刚才看好像他们已经修复了。

又去对比了一下 发现应该是版本号问题 Archive上的是 _20210510.10.30_ 而你这些天版本号写的是 _2022.0207_ 这种格式 估计系统对比觉得2021那个更大所以每天自动同步为Archive的那个了
![db](https://user-images.githubusercontent.com/19724779/153057297-8a26cb6f-dee2-4427-a888-498879c963d6.png)

**Comment by QIUZAIYOU** [comment]
确实，但是 Archive 的版本号我改不了，已经归档了。
添加了这里的代码为新的镜像源，重新安装下，应该会解决这个问题。
